############# default #############
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb # Fixes Davinci Resolve Issue
env = QT_QPA_PLATFORMTHEME,qt5ct
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# # GTK / QT stuff
# env = KDE_SESSION_VERSION, 6
# env = KDE_APPLICATIONS_AS_SCOPE,1 
# env = QT_WAYLAND_RECONNECT,1
# env = QT_AUTO_SCREEN_SCALE_FACTOR,0
#env = XDG_CONFIG_DIRS,~/.config/kdedefaults:/etc/xdg
#env = KDE_FULL_SESSION,true
#env = XDG_MENU_PREFIX,plasma-kbuildsycoca6
env = XDG_Quran_DIR,/home/pharmaracist/Quran
